import pickle
import torch
from torch.utils.data import Dataset
import networkx as nx
from concurrent.futures import ProcessPoolExecutor, as_completed
import os

from graph_rnn.helper import graph_to_matrix, get_attributes_len_for_graph_rnn, get_random_bfs_seq

MAX_WORKERS = os.cpu_count() if os.cpu_count() and os.cpu_count() > 2 else 1

class Graph_Adj_Matrix_from_file(Dataset):
    """
    Dataset for reading graphs from files and returning adjacency like matrices
    max_prev_node has higher precedence than max_head_and_tail i.e
    :param args: Args object
    :param graph_list: List of graph indices to be included in the dataset
    :param feature_map: feature_map for the dataset generated by the mapping
    :random_bfs: Whether or not to do random_bfs
    """

    def __init__(self, args, graph_list, feature_map, random_bfs=False):
        # Path to folder containing dataset
        self.dataset_path = args.current_processed_dataset_path
        self.graph_list = graph_list
        self.feature_map = feature_map
        # No. of previous nodes to consider for edge prediction
        self.max_prev_node = args.max_prev_node
        # Head and tail of adjacency vector to consider for edge prediction
        self.max_head_and_tail = args.max_head_and_tail
        self.random_bfs = random_bfs

        if self.max_prev_node is None and self.max_head_and_tail is None:
            print('Please provide max_prev_node or max_head_and_tail')
            exit()

        self.max_nodes = feature_map['max_nodes']
        len_node_vec, len_edge_vec, num_nodes_to_consider = get_attributes_len_for_graph_rnn(
            len(feature_map['node_forward']), len(feature_map['edge_forward']),
            self.max_prev_node, self.max_head_and_tail)
        self.feature_len = len_node_vec + num_nodes_to_consider * len_edge_vec

    def __len__(self):
        return len(self.graph_list)

    def __getitem__(self, idx):
        with open(self.dataset_path + 'graph' + str(self.graph_list[idx]) + '.dat', 'rb') as f:
            G = pickle.load(f)

        x_item = torch.zeros((self.max_nodes, self.feature_len))

        # get feature matrix for the min graph
        adj_feature_mat = graph_to_matrix(
            G, self.feature_map['node_forward'], self.feature_map['edge_forward'],
            self.max_prev_node, self.max_head_and_tail, self.random_bfs)

        # prepare x_item
        x_item[0:adj_feature_mat.shape[0],
               :adj_feature_mat.shape[1]] = adj_feature_mat

        return {'x': x_item, 'len': len(adj_feature_mat)}


class Graph_Adj_Matrix(Dataset):
    """
    Mainly for testing purposes
    Dataset for taking graphs list and returning adjacency like matrices
    :param graph_list: List of graphs to be included in the dataset
    :param feature_map: feature_map for the dataset generated by the mapping
    :param max_prev_node: No of previous nodes to consider for edge prediction
    :param max_head_and_tail: Head and tail of adjacency vector to consider for edge prediction
    :random_bfs: Whether or not to do random_bfs
    """

    def __init__(self, graph_list, feature_map, max_prev_node=None, max_head_and_tail=None, random_bfs=False):
        self.graph_list = graph_list
        self.feature_map = feature_map
        self.max_prev_node = max_prev_node
        self.max_head_and_tail = max_head_and_tail
        self.random_bfs = random_bfs

        if self.max_prev_node is None and self.max_head_and_tail is None:
            print('Please provide max_prev_node or max_head_and_tail')
            exit()

        self.max_nodes = feature_map['max_nodes']
        len_node_vec, len_edge_vec, num_nodes_to_consider = get_attributes_len_for_graph_rnn(len(
            feature_map['node_forward']), len(feature_map['edge_forward']), max_prev_node, max_head_and_tail)
        self.feature_len = len_node_vec + num_nodes_to_consider * len_edge_vec

    def __len__(self):
        return len(self.graph_list)

    def __getitem__(self, idx):
        G = self.graph_list[idx]

        x_item = torch.zeros((self.max_nodes, self.feature_len))

        # get feature matrix for the min graph
        adj_feature_mat = graph_to_matrix(
            G, self.feature_map['node_forward'], self.feature_map['edge_forward'], self.max_prev_node, self.max_head_and_tail, self.random_bfs)

        # prepare x_item
        x_item[0:adj_feature_mat.shape[0],
               :adj_feature_mat.shape[1]] = adj_feature_mat

        return {'x': x_item, 'len': len(adj_feature_mat)}


def mapping(graphs):
    """
    Create feature maps for nodes and edges from the list of graphs
    :param graphs: List of networkx graphs
    :return: feature_map dictionary
    """

    node_forward, node_backward = {}, {}
    edge_forward, edge_backward = {}, {}
    node_count, edge_count = 0, 0
    max_nodes, max_edges, max_degree = 0, 0, 0
    min_nodes, min_edges = float('inf'), float('inf')

    for G in graphs:
        max_nodes = max(max_nodes, len(G.nodes()))
        min_nodes = min(min_nodes, len(G.nodes()))
        for _, data in G.nodes.data():
            if data['label'] not in node_forward:
                node_forward[data['label']] = node_count
                node_backward[node_count] = data['label']
                node_count += 1

        max_edges = max(max_edges, len(G.edges()))
        min_edges = min(min_edges, len(G.edges()))
        for _, _, data in G.edges.data():
            if data['label'] not in edge_forward:
                edge_forward[data['label']] = edge_count
                edge_backward[edge_count] = data['label']
                edge_count += 1

        max_degree = max(max_degree, max([d for n, d in G.degree()]))

    feature_map = {
        'node_forward': node_forward,
        'node_backward': node_backward,
        'edge_forward': edge_forward,
        'edge_backward': edge_backward,
        'max_nodes': max_nodes,
        'min_nodes': min_nodes,
        'max_edges': max_edges,
        'min_edges': min_edges,
        'max_degree': max_degree
    }

    print('Successfully done node count', node_count)
    print('Successfully done edge count', edge_count)

    return feature_map

def calc_max_prev_node(graphs):
    """
    Approximate max_prev_node from simulating bfs sequences 
    """
    max_prev_node = []

    with ProcessPoolExecutor(max_workers=MAX_WORKERS) as executor:
        futures = [executor.submit(calc_max_prev_node_helper, graph) for graph in graphs]

        for i, future in enumerate(as_completed(futures), 1):
            print(f"Processing graph {i}/{len(graphs)}")
            max_node = future.result()
            if max_node is not None:
                max_prev_node.extend(max_node)

    max_prev_node = sorted(max_prev_node)[-1 * int(0.001 * len(max_prev_node))]
    return max_prev_node


def calc_max_prev_node_helper(G):

    max_prev_node = []
    for _ in range(100):
        bfs_seq = get_random_bfs_seq(G)
        bfs_order_map = {bfs_seq[i]: i for i in range(len(G.nodes()))}
        G = nx.relabel_nodes(G, bfs_order_map)

        max_prev_node_iter = 0
        for u, v in G.edges():
            max_prev_node_iter = max(max_prev_node_iter, max(u, v) - min(u, v))

        max_prev_node.append(max_prev_node_iter)

    return max_prev_node

